Added myself (ewenjo)
CodingGardenCommunity/contributors pull request #2
Opened 2019-03-07 19:51 UTC by ewenjo

2019-03-08 14:32 UTC, spiray approved these changes

2019-03-09 10:56 UTC, westborn approved these changes
All good

2019-03-12 03:01 UTC, w3cj requested changes
I've added the prettier formatter to the repo. Please pull the latest changes and run prettier.

```sh
git remote add coding-garden https://github.com/CodingGardenCommunity/contributors.git
git pull coding-garden master
npm install
npm run format
```

You may need to fix merge conflicts before running `npm run format`

2019-03-13 17:16 UTC, ewenjo commented
Updated.

2019-03-13 17:20 UTC, merged